//! FFI declarations for the C TNG compression library.
//!
//! These are hand-written rather than generated by bindgen to avoid
//! a clang/libclang dependency in CI. The API is small, stable, and
//! uses only primitive types.

use std::ffi::{c_int, c_uint, c_ulong};

// C `fix_t` is `unsigned long` — 64-bit on LP64 (Linux x86_64),
// 32-bit on LLP64 (Windows). Rust `c_ulong` matches this.
pub type FixT = c_ulong;

// ---------------------------------------------------------------------------
// rle.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_conv_to_rle(
        vals: *const c_uint,
        nvals: c_int,
        rle: *mut c_uint,
        nrle: *mut c_int,
        min_rle: c_int,
    );

    pub fn Ptngc_comp_conv_from_rle(rle: *const c_uint, vals: *mut c_uint, nvals: c_int);
}

// ---------------------------------------------------------------------------
// fixpoint.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_ud_to_fix_t(d: f64, max: f64) -> FixT;
    pub fn Ptngc_d_to_fix_t(d: f64, max: f64) -> FixT;
    pub fn Ptngc_fix_t_to_ud(f: FixT, max: f64) -> f64;
    pub fn Ptngc_fix_t_to_d(f: FixT, max: f64) -> f64;
    pub fn Ptngc_d_to_i32x2(d: f64, hi: *mut FixT, lo: *mut FixT);
    pub fn Ptngc_i32x2_to_d(hi: FixT, lo: FixT) -> f64;
}

// ---------------------------------------------------------------------------
// widemuldiv.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_largeint_add(v1: c_uint, largeint: *mut c_uint, n: c_int);

    pub fn Ptngc_largeint_mul(
        v1: c_uint,
        largeint_in: *mut c_uint,
        largeint_out: *mut c_uint,
        n: c_int,
    );

    pub fn Ptngc_largeint_div(
        v1: c_uint,
        largeint_in: *mut c_uint,
        largeint_out: *mut c_uint,
        n: c_int,
    ) -> c_uint;
}

// ---------------------------------------------------------------------------
// bwt.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_to_bwt(
        vals: *mut c_uint,
        nvals: c_int,
        output: *mut c_uint,
        index: *mut c_int,
    );
    pub fn Ptngc_comp_from_bwt(input: *mut c_uint, nvals: c_int, index: c_int, vals: *mut c_int);
    pub fn Ptngc_bwt_merge_sort_inner(
        indices: *mut c_int,
        nvals: c_int,
        vals: *mut c_uint,
        start: c_int,
        end: c_int,
        nrepeat: *mut c_uint,
        workarray: *mut c_int,
    );
}

// ---------------------------------------------------------------------------
// vals16.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_conv_to_vals16(
        vals: *const c_uint,
        nvals: c_int,
        vals16: *mut c_uint,
        nvals16: *mut c_int,
    );
    pub fn Ptngc_comp_conv_from_vals16(
        vals16: *const c_uint,
        nvals16: c_int,
        vals: *mut c_int,
        nvals: *mut c_int,
    );
}
