//! FFI declarations for the C TNG compression library.
//!
//! These are hand-written rather than generated by bindgen to avoid
//! a clang/libclang dependency in CI. The API is small, stable, and
//! uses only primitive types.

use std::ffi::{c_int, c_uint, c_ulong};

// C `fix_t` is `unsigned long` — 64-bit on LP64 (Linux x86_64),
// 32-bit on LLP64 (Windows). Rust `c_ulong` matches this.
pub type FixT = c_ulong;

// ---------------------------------------------------------------------------
// rle.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_conv_to_rle(
        vals: *const c_uint,
        nvals: c_int,
        rle: *mut c_uint,
        nrle: *mut c_int,
        min_rle: c_int,
    );

    pub fn Ptngc_comp_conv_from_rle(rle: *const c_uint, vals: *mut c_uint, nvals: c_int);
}

// ---------------------------------------------------------------------------
// fixpoint.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_ud_to_fix_t(d: f64, max: f64) -> FixT;
    pub fn Ptngc_d_to_fix_t(d: f64, max: f64) -> FixT;
    pub fn Ptngc_fix_t_to_ud(f: FixT, max: f64) -> f64;
    pub fn Ptngc_fix_t_to_d(f: FixT, max: f64) -> f64;
    pub fn Ptngc_d_to_i32x2(d: f64, hi: *mut FixT, lo: *mut FixT);
    pub fn Ptngc_i32x2_to_d(hi: FixT, lo: FixT) -> f64;
}

// ---------------------------------------------------------------------------
// widemuldiv.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_largeint_add(v1: c_uint, largeint: *mut c_uint, n: c_int);

    pub fn Ptngc_largeint_mul(
        v1: c_uint,
        largeint_in: *mut c_uint,
        largeint_out: *mut c_uint,
        n: c_int,
    );

    pub fn Ptngc_largeint_div(
        v1: c_uint,
        largeint_in: *mut c_uint,
        largeint_out: *mut c_uint,
        n: c_int,
    ) -> c_uint;
}

// ---------------------------------------------------------------------------
// bwt.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_to_bwt(
        vals: *mut c_uint,
        nvals: c_int,
        output: *mut c_uint,
        index: *mut c_int,
    );
    pub fn Ptngc_comp_from_bwt(input: *mut c_uint, nvals: c_int, index: c_int, vals: *mut c_int);
    pub fn Ptngc_bwt_merge_sort_inner(
        indices: *mut c_int,
        nvals: c_int,
        vals: *mut c_uint,
        start: c_int,
        end: c_int,
        nrepeat: *mut c_uint,
        workarray: *mut c_int,
    );
}

// ---------------------------------------------------------------------------
// vals16.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_conv_to_vals16(
        vals: *const c_uint,
        nvals: c_int,
        vals16: *mut c_uint,
        nvals16: *mut c_int,
    );
    pub fn Ptngc_comp_conv_from_vals16(
        vals16: *const c_uint,
        nvals16: c_int,
        vals: *mut c_int,
        nvals: *mut c_int,
    );
}

// ---------------------------------------------------------------------------
// tng_compress.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    // Position compression
    pub fn tng_compress_pos(
        pos: *mut f64,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f64,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_pos_float(
        pos: *mut f32,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f32,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_pos_int(
        pos: *mut c_int,
        natoms: c_int,
        nframes: c_int,
        prec_hi: c_ulong,
        prec_lo: c_ulong,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    // Velocity compression
    pub fn tng_compress_vel(
        vel: *mut f64,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f64,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_vel_float(
        vel: *mut f32,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f32,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_vel_int(
        vel: *mut c_int,
        natoms: c_int,
        nframes: c_int,
        prec_hi: c_ulong,
        prec_lo: c_ulong,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    // Find-algo variants
    pub fn tng_compress_pos_find_algo(
        pos: *mut f64,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f64,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_pos_float_find_algo(
        pos: *mut f32,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f32,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_pos_int_find_algo(
        pos: *mut c_int,
        natoms: c_int,
        nframes: c_int,
        prec_hi: c_ulong,
        prec_lo: c_ulong,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_vel_find_algo(
        vel: *mut f64,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f64,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_vel_float_find_algo(
        vel: *mut f32,
        natoms: c_int,
        nframes: c_int,
        desired_precision: f32,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    pub fn tng_compress_vel_int_find_algo(
        vel: *mut c_int,
        natoms: c_int,
        nframes: c_int,
        prec_hi: c_ulong,
        prec_lo: c_ulong,
        speed: c_int,
        algo: *mut c_int,
        nitems: *mut c_int,
    ) -> *mut i8;

    // Decompression & inquiry
    pub fn tng_compress_inquire(
        data: *mut i8,
        vel: *mut c_int,
        natoms: *mut c_int,
        nframes: *mut c_int,
        precision: *mut f64,
        algo: *mut c_int,
    ) -> c_int;

    pub fn tng_compress_uncompress(data: *mut i8, posvel: *mut f64) -> c_int;
    pub fn tng_compress_uncompress_float(data: *mut i8, posvel: *mut f32) -> c_int;

    pub fn tng_compress_nalgo() -> c_int;
}

// ---------------------------------------------------------------------------
// coder.h
// ---------------------------------------------------------------------------
#[repr(C)]
pub struct Coder {
    pack_temporary: c_uint,
    pack_temporary_bits: c_int,
    stat_overflow: c_int,
    stat_numval: c_int,
}

unsafe extern "C" {
    pub fn Ptngc_coder_init() -> *mut Coder;
    pub fn Ptngc_coder_deinit(coder: *mut Coder);
    pub fn Ptngc_pack_array(
        coder: *mut Coder,
        input: *mut c_int,
        length: *mut c_int,
        coding: c_int,
        coding_parameter: c_int,
        natoms: c_int,
        speed: c_int,
    ) -> *mut u8;
    pub fn Ptngc_unpack_array(
        coder: *mut Coder,
        packed: *mut u8,
        output: *mut c_int,
        length: c_int,
        coding: c_int,
        coding_parameter: c_int,
        natoms: c_int,
    ) -> c_int;
}

// ---------------------------------------------------------------------------
// dict.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_make_dict(
        vals: *const c_uint,
        nvals: c_int,
        dict: *mut c_uint,
        ndict: *mut c_int,
        hist: *mut c_uint,
    );
}

// ---------------------------------------------------------------------------
// mtf.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_conv_to_mtf(
        vals: *const c_uint,
        nvals: c_int,
        dict: *const c_uint,
        ndict: c_int,
        valsmtf: *mut c_uint,
    );

    pub fn Ptngc_comp_conv_from_mtf(
        valsmtf: *const c_uint,
        nvals: c_int,
        dict: *const c_uint,
        ndict: c_int,
        vals: *mut c_uint,
    );

    pub fn Ptngc_comp_conv_to_mtf_partial(vals: *const c_uint, nvals: c_int, valsmtf: *mut c_uint);

    pub fn Ptngc_comp_conv_from_mtf_partial(
        valsmtf: *const c_uint,
        nvals: c_int,
        vals: *mut c_uint,
    );

    pub fn Ptngc_comp_conv_to_mtf_partial3(vals: *const c_uint, nvals: c_int, valsmtf: *mut u8);

    pub fn Ptngc_comp_conv_from_mtf_partial3(valsmtf: *mut u8, nvals: c_int, vals: *mut c_uint);
}
// ---------------------------------------------------------------------------
// dict.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_make_dict_hist(
        vals: *const c_uint,
        nvals: c_int,
        dict: *mut c_uint,
        ndict: *mut c_int,
        hist: *mut c_uint,
    );
}

// ---------------------------------------------------------------------------
// huffman.h
// ---------------------------------------------------------------------------
unsafe extern "C" {
    pub fn Ptngc_comp_conv_to_huffman(
        vals: *const c_uint,
        nvals: c_int,
        dict: *const c_uint,
        ndict: c_int,
        prob: *mut c_uint,
        huffman: *mut u8,
        huffman_len: *mut c_int,
        huffman_dict: *mut u8,
        huffman_dictlen: *mut c_int,
        huffman_dict_unpacked: *mut c_uint,
        huffman_dict_unpackedlen: *mut c_int,
    );
    pub fn Ptngc_comp_conv_from_huffman(
        huffman: *mut u8,
        vals: *mut c_uint,
        nvals: c_int,
        ndict: c_int,
        huffman_dict: *mut u8,
        huffman_dictlen: c_int,
        huffman_dict_unpacked: *const c_uint,
        huffman_dict_unpackedlen: c_int,
    );
}
