use crate::{
    coder::Coder,
    widemuldiv::{ptngc_largeint_add, ptngc_largeint_mul},
    xtc3::positive_int,
};

// This magic value is generated by max_magic.py in the original c code
const MAX_MAGIC: usize = 92;

#[rustfmt::skip]
const MAGIC: [u32; MAX_MAGIC] = [
    2,          3,         4,          5,          6,          8,          10,
    12,         16,        20,         25,         32,         40,         50,
    64,         80,        101,        128,        161,        203,        256,
    322,        406,       512,        645,        812,        1024,       1290,
    1625,       2048,      2580,       3250,       4096,       5160,       6501,
    8192,       10321,     13003,      16384,      20642,      26007,      32768,
    41285,      52015,     65536,      82570,      104031,     131072,     165140,
    208063,     262144,    330280,     416127,     524288,     660561,     832255,
    1048576,    1321122,   1664510,    2097152,    2642245,    3329021,    4194304,
    5284491,    6658042,   8388608,    10568983,   13316085,   16777216,   21137967,
    26632170,   33554432,  42275935,   53264340,   67108864,   84551870,   106528681,
    134217728,  169103740, 213057362,  268435456,  338207481,  426114725,  536870912,
    676414963,  852229450, 1073741824, 1352829926, 1704458900, 2147483648, 2705659852,
    3408917801,
];

pub(crate) const fn ptngc_magic(i: usize) -> u32 {
    MAGIC[i]
}

pub(crate) fn ptngc_find_magic_index(maxval: u32) -> u32 {
    let mut i;

    if maxval > MAGIC[MAX_MAGIC / 4] {
        if maxval > MAGIC[MAX_MAGIC / 2] {
            i = MAX_MAGIC / 2 + 1;
        } else {
            i = MAX_MAGIC / 4 + 1;
        }
    } else {
        i = 0;
    }

    while MAGIC[i] <= maxval {
        i += 1;
    }
    i.try_into().expect("u32 from usize")
}

pub(crate) fn ptngc_pack_array_xtc2(
    coder: &mut Coder,
    input: &mut [i32],
    length: &mut usize,
) -> Vec<u8> {
    let ntriplets = *length / 3;
    let mut maxint = [input[0], input[1], input[2]];
    let mut minint = [input[0], input[1], input[2]];
    let mut output = Vec::with_capacity(8 * *length);

    for i in 1..ntriplets {
        for j in 0..3 {
            if input[i * 3 + j] > maxint[j] {
                maxint[j] = input[i * 3 + j];
            }
            if input[i * 3 + j] < minint[j] {
                minint[j] = input[i * 3 + j];
            }
        }
    }

    let large_index = [
        ptngc_find_magic_index(u32::try_from(maxint[0] - minint[0] + 1).expect("u32 from i32")),
        ptngc_find_magic_index(u32::try_from(maxint[1] - minint[1] + 1).expect("u32 from i32")),
        ptngc_find_magic_index(u32::try_from(maxint[2] - minint[2] + 1).expect("u32 from i32")),
    ];
    let large_nbits = compute_magic_bits(large_index);
    let max_large_index = *large_index.iter().max().unwrap();

    // Guess the initial small index
    let mut small_index = max_large_index / 2;

    // Find the largest value that is not large. Not large is half index of large
    let max_small = MAGIC[usize::try_from(small_index).expect("usize from u32")];
    let mut intmax = 0;
    for item in &input[..*length] {
        let s = positive_int(*item);
        if s > intmax && s < max_small {
            intmax = s;
        }
    }
    // This value is not critical, since if I guess wrong, the code will
    // just insert instructions to increase this value
    small_index = ptngc_find_magic_index(intmax);

    // Store min integers
    coder.pack_temporary_bits = 32;
    coder.pack_temporary = positive_int(minint[0]);
    coder.out8bits_vec(&mut output);
    coder.pack_temporary_bits = 32;
    coder.pack_temporary = positive_int(minint[1]);
    coder.out8bits_vec(&mut output);
    coder.pack_temporary_bits = 32;
    coder.pack_temporary = positive_int(minint[2]);
    coder.out8bits_vec(&mut output);
    // Store max indices
    coder.pack_temporary_bits = 8;
    coder.pack_temporary = large_index[0];
    coder.out8bits_vec(&mut output);
    coder.pack_temporary_bits = 8;
    coder.pack_temporary = large_index[1];
    coder.out8bits_vec(&mut output);
    coder.pack_temporary_bits = 8;
    coder.pack_temporary = large_index[2];
    coder.out8bits_vec(&mut output);
    // Store initial small index
    coder.pack_temporary_bits = 8;
    coder.pack_temporary = small_index;
    coder.out8bits_vec(&mut output);

    // Initial prevcoord is the minimum integers
    unimplemented!("line 1745 xtc2.c");

    output
}

// Compute number of bits required to store values using three different bases in the index array
fn compute_magic_bits(index: [u32; 3]) -> usize {
    let mut largeint = [0; 4];
    let mut largeint_tmp = [0; 4];

    for i in 0..3 {
        if i != 0 {
            // We must do the multiplication of the largeint with the integer base
            ptngc_largeint_mul(
                MAGIC[usize::try_from(index[i]).expect("usize from u32")],
                &mut largeint,
                &mut largeint_tmp,
                4,
            );
            for j in 0..4 {
                largeint[j] = largeint_tmp[j];
            }
        }
        ptngc_largeint_add(
            MAGIC[usize::try_from(index[i]).expect("usize from u32")] - 1,
            &mut largeint,
            4,
        );
    }
    // Find last bit
    let mut onebit = 0;
    for i in 0..3 {
        for j in 0..32 {
            if (largeint[i] & (1 << j)) > 0 {
                onebit = i * 32 + j + 1;
            }
        }
    }
    onebit
}
